# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(525, 386)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        # self.image_label = QtWidgets.QLabel(Form)
        # self.image_label.setObjectName("image_label")
        # # self.image_label.setGeometry(QtCore.QRect(20, 70, 100, 100))
        # self.verticalLayout.addWidget(self.image_label)
        self.control_bt = QtWidgets.QPushButton(Form)
        self.control_bt.setObjectName("control_bt")
        self.control_bt.setMaximumHeight(40)
        self.control_bt.setMaximumWidth(70)
        self.verticalLayout.addWidget(self.control_bt)
        self.rectangle = QtWidgets.QPushButton(Form)
        self.rectangle.setObjectName("rectangle")
        self.rectangle.setMaximumHeight(40)
        self.rectangle.setMaximumWidth(70)
        self.verticalLayout.addWidget(self.rectangle)
        self.line = QtWidgets.QPushButton(Form)
        self.line.setObjectName("line")
        self.line.setMaximumHeight(40)
        self.line.setMaximumWidth(70)
        self.verticalLayout.addWidget(self.line)
        self.Undo = QtWidgets.QPushButton(Form)
        self.Undo.setObjectName("Undo")
        self.Undo.setMaximumHeight(40)
        self.Undo.setMaximumWidth(70)
        self.verticalLayout.addWidget(self.Undo)
        self.save = QtWidgets.QPushButton(Form)
        self.save.setObjectName("save")
        self.save.setMaximumHeight(40)
        self.save.setMaximumWidth(70)
        self.verticalLayout.addWidget(self.save)
        self.Reset = QtWidgets.QPushButton(Form)
        self.Reset.setObjectName("Reset")
        self.Reset.setMaximumHeight(40)
        self.Reset.setMaximumWidth(70)        
        self.verticalLayout.addWidget(self.Reset)
        self.TDL = QtWidgets.QPushButton(Form)
        self.TDL.setObjectName("TDL")
        self.TDL.setMaximumHeight(40)
        self.TDL.setMaximumWidth(70)        
        self.verticalLayout.addWidget(self.TDL)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout")
        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setObjectName("image_label")
        self.verticalLayout2.addWidget(self.image_label)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.Prev = QtWidgets.QPushButton(Form)
        self.Prev.setObjectName("Prev")
        # self.Prev.setMaximumHeight(40)
        # self.Prev.setMaximumWidth(70)
        self.horizontalLayout2.addWidget(self.Prev)
        self.Next = QtWidgets.QPushButton(Form)
        self.Next.setObjectName("Next")
        # self.Next.setMaximumHeight(40)
        # self.Next.setMaximumWidth(70)
        self.horizontalLayout2.addWidget(self.Next)
        self.verticalLayout2.addLayout(self.horizontalLayout2)
        self.horizontalLayout.addLayout(self.verticalLayout2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cam view"))
        self.image_label.setText(_translate("Form", "TextLabel"))
        self.control_bt.setText(_translate("Form", "Start"))
        self.rectangle.setText(_translate("Form", "Rectangle"))
        self.line.setText(_translate("Form", "line"))
        self.Undo.setText(_translate("Form", "Undo"))
        self.save.setText(_translate("Form", "save"))
        self.Reset.setText(_translate("Form", "Reset"))
        self.TDL.setText(_translate("Form", "TDL"))
        self.Next.setText(_translate("Form", "Next"))
        self.Prev.setText(_translate("Form", "Prev"))

class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(465, 432)
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(140, 20, 201, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 101, 16))
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 101, 16))
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 101, 16))
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_1.setGeometry(QtCore.QRect(140, 70, 161, 21))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 110, 161, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 150, 161, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 230, 91, 31))
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton1 = QtWidgets.QPushButton(Form)
        self.pushButton1.setGeometry(QtCore.QRect(200, 230, 91, 31))
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Login Forms"))
        self.label_2.setText(_translate("Form", "Email"))
        self.label_3.setText(_translate("Form", "Username"))
        self.label_4.setText(_translate("Form", "Password"))        
        self.pushButton.setText(_translate("Form", "Login"))
        self.pushButton1.setText(_translate("Form", "Register"))


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(465, 432)
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(140, 20, 201, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 101, 16))
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 101, 16))
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 101, 16))
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 101, 16))
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_1.setGeometry(QtCore.QRect(140, 70, 161, 21))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 110, 161, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 150, 161, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 190, 161, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 230, 91, 31))
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton1 = QtWidgets.QPushButton(Form)
        self.pushButton1.setGeometry(QtCore.QRect(200, 230, 91, 31))
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Registration"))
        self.label_2.setText(_translate("Form", "Name"))
        self.label_3.setText(_translate("Form", "Email"))
        self.label_4.setText(_translate("Form", "Username"))        
        self.label_5.setText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "Register"))
        self.pushButton1.setText(_translate("Form", "Login"))
